### ISSUE TITLE
Low-Res textures

### ISSUE THREAD

**Issue by leothehero** [beccabunny/Animated-ships#6]
The animated textures are much more low-res and less polished/updated than the original textures for ships such as the Dreadnought in the latest steam release, is this something that will be fixed in the future?
![image](https://user-images.githubusercontent.com/20319418/70662573-cd032a00-1c66-11ea-86d2-fd0ea4a7e219.png)

**Comment by beccabunny** [comment]
They aren't low res, they are simply the 0.9.9 version of the ship instead of the 0.9.10. I will not update them, as I am not working on this mod anymore
